### PR TITLE
Removed adas from human pose estimation name in readme

### PR DESCRIPTION
**Pull request by Daniil-Osokin**
Removed `adas` from model name in demos readme.

### CODE REVIEW

**Comment by Daniil-Osokin** [comment]
@vmatveic Cleaned readme for human pose estimation.

**Comment by vmatveic** [comment]
Hi @Daniil-Osokin ,
Should it be  re-targeted to the develop branch? @IRDonch @kchechil @snosov1 , please confirm

**Comment by IRDonch** [comment]
At this point it's not necessary, because I'm about to merge `develop` into `master` anyway. However, be prepared to rebase.

**Comment by IRDonch** [comment]
@Daniil-Osokin Mind rebasing?

**Comment by Daniil-Osokin** [comment]
Rebased.

**Pull request merged**
