### PR TITLE
Add requirements files for Model Downloader CI

### PR DESCRIPTION
**Pull request by IRDonch**

### CODE REVIEW

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Pull request merged**
