### PR TITLE
update ref metric values for person-vehicle-bike-detection-crossroad-0078

### PR DESCRIPTION
**Pull request by vladimir-dudnik**
originally, ref metrics were obtained with IR from some old OpenVINO version and unknown OpenCV version. This PR updates metrics with using model in source framework format and OpenCV 4.1.1-openvino

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
@snosov1 could you please take a look on proposed change?

**Comment by vladimir-dudnik** [comment]
> Vladimir, thanks for improving the accuracy of our detector!
This is a joke of course. Just use better defined environment to compute metric. No changes in detector applied.

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
precommit is red because http://iitlab.bit.edu.cn/mcislab/vehicledb/ is not active

**Comment by snosov1** [comment]
> precommit is red because http://iitlab.bit.edu.cn/mcislab/vehicledb/ is not active

yeah, that's, actually, an issue. Unless BIT-Vehicle becomes active again, we'll have to figure out how to work around it.

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Pull request merged**
