### PR TITLE
fixed links to demos readme.md files

### PR DESCRIPTION
**Pull request by azaytsev1980**

### CODE REVIEW

**Comment by kchechil** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
@azaytsev1980 what for do we need to change relative links to relative links?

**Comment by azaytsev1980** [comment]
@Wovchena The changes are needed so that our documentation generation system can set these links properly: "./" is required

**Comment by azaytsev1980** [comment]
@zmaslova @Wovchena @kchechil Thanks!

**Pull request merged**
