### PR TITLE
ci/requirements-*.txt: bump all versions

### PR DESCRIPTION
**Pull request by IRDonch**
~Except for numpy in `requirements-ac.txt`, which needs to stay at 1.16 due to an issue with Pylint.~

EDIT: Bumped numpy too.

### CODE REVIEW

**Comment by eaidova** [comment]
> Except for numpy in requirements-ac.txt, which needs to stay at 1.16 due to an issue with Pylint

Pylint issue: https://github.com/PyCQA/pylint/issues/2865
looks like it was fixed in the last pylint version, but I need additional check

**Comment by IRDonch** [comment]
> looks like it was fixed in the last pylint version, but I need additional check

Oh, that's great to know. Let me know if you confirm it.

**Comment by eaidova** [comment]
@IRDonch , pylint 2.3.1(+ astroid 2.2.5)  successfuly works with numpy 1.16.1  and higher.
But it detects one new issue, which I fix in https://github.com/opencv/open_model_zoo/pull/294

**Comment by IRDonch** [comment]
Alright, in that case I'll bump NumPy too after #294 is merged.

**Comment by eaidova** [comment]
@IRDonch , another requirement which can not be bumped is py-cpuinfo==4.0.0 (the next release has the bug with showing CPU flags from frozen code, it is not fixed yet). But we use this lib only for cpu_extension loading. As I know, CPU extension is going to be a part of CPU plugin in R3, so probably it makes sense to remove this lib from accuracy checker dependency at all.

**Comment by IRDonch** [comment]
> another requirement which can not be bumped is py-cpuinfo==4.0.0

Good thing I didn't bump it then, right? :-)

(I use `pip-compile` to build these files, so I automatically obey all requirements set by `setup.py`.)

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Pull request merged**
