### PR TITLE
Add YOLOv3 or Tiny YOLOv3 Support to Multiple Channel Sample Code for OpenVINO R2

### PR DESCRIPTION
**Pull request by FengYen-Chang**

### CODE REVIEW

**Comment by FengYen-Chang** [comment]
Sorry for duplicate several commits, please check the last 8 commits for this sample. Thanks:)

**Comment by snosov1** [comment]
Hey, @FengYen-Chang !

I suggest that you leave only the stuff related to Yolov3 support in Multi-Channel demo in this PR. Otherwise, the reviewers won't give it a go.

**Comment by FengYen-Chang** [comment]
Hi @snosov1,
Thanks for your suggestion, I will made a new PR from another branch and close this PR.

Hi @IRDonch,  
Yeah, To remove this, I will made a new PR from another branch and close this PR.

**Comment by snosov1** [comment]
Reopened as https://github.com/opencv/open_model_zoo/pull/448

**Pull request closed without merging**
