### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by matrix-2020**
Just creat a PR for bert demo, code may not comply with the required process and license.

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
what is the reason to create PR which may not comply with requirement and especially, license? Please follow steps described in  OMZ [contributing](https://github.com/opencv/open_model_zoo/blob/develop/CONTRIBUTING.md) guide

**Comment by matrix-2020** [comment]
Just notice there is demo/sample code for BERT model, you can close this PR if the code is not complied with OMZ contributing guide.

**Comment by IRDonch** [comment]
If you don't follow the contribution process, then we can't accept your contribution. Closing.

**Comment by wdkwyf** [comment]
Hi, Can I work on this pull request to upload a bert-fine-tuned-on-squad2 models. 
I notice a lot of great work has been done and I wonder if there is already existing work?

**Comment by vladimir-dudnik** [comment]
Hi @wdkwyf yes we consider to add BERT model and demo to OMZ this year

**Comment by wdkwyf** [comment]
@vladimir-dudnik OK, we'll drop this PR because existing work~

**Pull request closed without merging**
