### PR TITLE
Standardize documentation regarding accuracy metrics

### PR DESCRIPTION
**Pull request by dkustikx**
Standardize documentation regarding accuracy metrics

### CODE REVIEW

**Comment by Wovchena** [comment]
@AlexKoff88, it seems you are not included in [opencv organization](https://github.com/opencv) and I can not assign this PR to you. Please, review.

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Pull request merged**
