### PR TITLE
Created support for IP-cameras through RSTP

### PR DESCRIPTION
**Pull request by durgabhavaniv**
Able to take take input form ip cameras for running demo samples

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@durgabhavaniv Please re-target your PR to **develop** branch.

**Comment by durgabhavaniv** [comment]
@vladimir-dudnik re-targeted PR to develop branch.

**Comment by durgabhavaniv** [comment]
@vladimir-dudnik got this message "This branch has conflicts that must be resolved"

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
@durgabhavaniv you may close this PR as we not going to merge that to master branch

**Pull request closed without merging**
