### PR TITLE
Update typo error faster_rcnn_inception_v2_coco.md

### PR DESCRIPTION
**Pull request by immehulsolanki**
Corrected typo error.

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@immehulsolanki thanks for fixing typo

**Comment by immehulsolanki** [comment]
Hi  vladimir-dudnik,
Typo error still not reflated in online file, its still there,
how to fix it!?

**Comment by vladimir-dudnik** [comment]
@immehulsolanki I've missed that your PR was targeted to `master` branch. This branch corresponds to the latest OpenVINO release. In the [CONTRIBUTING.md](https://github.com/opencv/open_model_zoo/blob/develop/CONTRIBUTING.md) file, we recommend to make PR to `develop` branch. So, I've reverted this change in `master` branch and re-target the fix to `develop` branch.

**Comment by immehulsolanki** [comment]
Hi vladimir-dudnik,.
Thanks for you response, Yes change applied  in developed branch.
Now i wonder how to apply same in original master branch. Will it fixed from your side? i think it would be better for such a small change.

Thank You.

**Comment by vladimir-dudnik** [comment]
@immehulsolanki as I've said `master` branch corresponds to the latest OpenVINO release (2020.2 at the moment) and typo have existed in this already released version. We can not change the past (but at least should be able to learn from it)

**Pull request merged**
