### PR TITLE
modify security_barrier_camera_demo readme for using all Intel® Vision Accelerator Design with Intel® Movidius™ VPUs computation ability

### PR DESCRIPTION
**Pull request by zhaixuejun1993**
modify security_barrier_camera_demo readme for using all Intel® Vision Accelerator Design with Intel® Movidius™ VPUs computation ability.
(1) -n_iqs 10: associated with the number of cores in  Intel® Vision Accelerator Design with Intel® Movidius™ VPUs.
(2) -n_wt 4: associated with the number of cores in CPU 
(3) -nireq 10: associated with the number of cores in  Intel® Vision Accelerator Design with Intel® Movidius™ VPUs.

### CODE REVIEW

**Comment by zhaixuejun1993** [comment]
Of course, any one of the admins can verify this patch. The old PR has been removed, this is a new one. Thanks.

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by zhaixuejun1993** [comment]
> Please, retarget to `opencv:develop`.
> 
> The changes look good.

The new PR have be created (https://github.com/opencv/open_model_zoo/pull/443) please review

**Comment by IRDonch** [comment]
I assume this one is obsoleted by #443; closing.

**Pull request closed without merging**
