### PR TITLE
demos: remove unused headers from common

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Comment by Wovchena** [comment]
@IRDonch we need newer dldt to pass builds :)

**Comment by Wovchena** [comment]
@IRDonch we need newer dldt to pass builds :)

**Comment by IRDonch** [comment]
If these headers change from release to release, maybe we shouldn't be including them in the first place. How about including `<inference_engine.h>` instead? That ought to work on all versions.

**Comment by Wovchena** [comment]
I am agree. Moreover, it appears that common does not need most of its IE includes. Updated

**Pull request merged**
