### PR TITLE
Update facial-landmarks-35-adas-0001.md

### PR DESCRIPTION
**Pull request by banderlog**
#47

### CODE REVIEW

**Comment by snosov1** [comment]
@kchechil Kirill, I'm ok with the change. Is it ok to merge?

**Comment by kchechil** [comment]
@snosov1 the model is going to be replaced with facial-landmarks-35-adas-0002 (which is more VPU-friendly) in R1'19.

**Comment by kchechil** [comment]
@snosov1 @banderlog  I've checked facial-landmarks-35-adas-0002.md and the only phrase that is probably missing there is "Expected color order is BGR."
Please feel free to submit PR against facial-landmarks-35-adas-0002.md. Thanks.

**Comment by asmorkalov** [comment]
Jenkins please retry a build

**Comment by snosov1** [comment]
Actually, I think we can close this PR, since the 0001 model was replaced by 0002. The doc for the 0002 doesn't seem to have the misleading sentence. @banderlog, makes sense?

**Comment by banderlog** [comment]
Fair enough

**Comment by snosov1** [comment]
Thx for the find!

**Pull request closed without merging**
