### PR TITLE
[FREEZED] Pytorch to onnx converter

### PR DESCRIPTION
**Pull request by eizamaliev**
Supports conversion to IR for models from Pytorch framework (see #152 pull request)

### CODE REVIEW

**Comment by eizamaliev** [comment]
@IRDonch please review
cc @kchechil

**Comment by IRDonch** [comment]
There's something strange going on with the history. I can see my own commits in the diff. Could you rebase your branch on top of `develop`?

**Comment by eizamaliev** [comment]
@IRDonch please review and merge

**Comment by IRDonch** [comment]
This was incorporated into #152, so I'm going to close it.

**Pull request closed without merging**
