### PR TITLE
Fix shapes in text-encoder/decoder models

### PR DESCRIPTION
**Pull request by aalborov**

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by aalborov** [comment]
> please retarget PR to develop branch

@vladimir-dudnik Done. How can I view what's wrong with the doc build?

**Comment by eaidova** [comment]
@aalborov @vladimir-dudnik  the failure is not connected with changes, looks like VOC server timely was unavilable:
```23:06:45  ERROR: 1 dead links found!
23:06:45  [✖] http://host.robots.ox.ac.uk/pascal/VOC/pubs/everingham10.pdf → Status: 0
23:06:45  [Pipeline] echo
23:06:45  [Error] Found broken links in intel/vehicle-detection-adas-binary-0001/description/vehicle-detection-adas-binary-0001.md
```

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Pull request merged**
