### PR TITLE
Bump dependency versions

### PR DESCRIPTION
**Pull request by IRDonch**
Unfortunately, pytorch/vision#2132 prevents us from moving to PyTorch 1.5, so I had to cap it at 1.4.

### CODE REVIEW

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by eaidova** [comment]
@IRDonch I want to move pillow from requirements.in to requirements-core.in (reason is enable segmentation models support by default)
see: https://github.com/opencv/open_model_zoo/pull/1306
can I do it before your dependencies bumping?

**Comment by IRDonch** [comment]
@eaidova Does your change conflict with mine in any way? Pillow is already in `ci/requirements-ac.txt`.

**Comment by eaidova** [comment]
> @eaidova Does your change conflict with mine in any way? Pillow is already in `ci/requirements-ac.txt`.

I believe this comment will be changed if I run updating requirements script.
 `# via -r tools/accuracy_checker/requirements.in, imageio, scikit-image`
If it is not problem, then we can do not pay attention

**Comment by IRDonch** [comment]
I don't think there's a need to update `ci/requirements-ac.txt` if all it does is change a comment.

**Comment by vladimir-dudnik** [comment]
@IRDonch moving from ubuntu 16.04 to 18.04 in 2021.1 release it seems we do not have this limitation anymore?

**Comment by IRDonch** [comment]
@vladimir-dudnik Do you mean the restriction on PyTorch < 1.5? If so, yes, that restriction was only necessary for Python 3.5 support, which will be dropped in 2021.1.

**Pull request merged**
