### PR TITLE
handwritten-score-recognition-0003

### PR DESCRIPTION
**Pull request by Ilya-Krylov**
@snosov1

### CODE REVIEW

**Comment by Ilya-Krylov** [comment]
@snosov1

**Comment by vladimir-dudnik** [comment]
@Ilya-Krylov please retarget PR to develop branch

**Comment by kchechil** [comment]
@Ilya-Krylov  please change target branch to opencv:develop, merge to master is on hold till R2 release.

**Comment by Ilya-Krylov** [comment]
Jenkins please retry a build

**Comment by kchechil** [comment]
Jenkins please retry a build

**Comment by kchechil** [comment]
Jenkins please retry a build

**Pull request merged**
