### PR TITLE
move samples to dldt

### PR DESCRIPTION
**Pull request by Wovchena**

### CODE REVIEW

**Comment by Wovchena** [comment]
this is supposed to be assigned to @IRDonch

**Comment by IRDonch** [comment]
add to whitelist

**Comment by IRDonch** [comment]
For the renamed demo, you should also change the target name.

**Comment by kchechil** [comment]
@Wovchena is it still actual? please rebase and prepare PR to merge to develop

**Comment by Wovchena** [comment]
reopened to merge into develop: https://github.com/opencv/open_model_zoo/pull/118

**Pull request closed without merging**
