### PR TITLE
Specified models for pedestrian_tracker_demo

### PR DESCRIPTION
**Pull request by dkustikx**
Specified list of supported models.
Models are not supported by this demo: person-detection-retail-0002, person-reidentification-retail-0076, person-reidentification-retail-0079.

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by kchechil** [comment]
cc @IRDonch

**Comment by IRDonch** [comment]
Sounds like a bug in the demo to me.

**Comment by IRDonch** [comment]
@Wovchena So would it be possible to update `pedestrian_tracker_demo` to make it work with the other model variants? From the descriptions, it doesn't sound like they're that different.

**Comment by Wovchena** [comment]
- I am suggesting to keep ReID models consistent. Currently `person-reidentification-retail-0079` and `person-reidentification-retail-0076` have output shape of [1, 256, 1, 1], while `person-reidentification-retail-0031` - [1, 256], but [person-reidentification-retail-0031.md](https://github.com/opencv/open_model_zoo/blob/master/intel_models/person-reidentification-retail-0031/description/person-reidentification-retail-0031.md#outputs) claims it's [1, 256, 1, 1]. I think [1, 256] makes more sense. The demo expects [1, 256].
- There is an update for detection part: https://github.com/opencv/open_model_zoo/pull/286

**Comment by kchechil** [comment]
@snosov1 @Ilya-Krylov  is it possible to align all reid models to the same output format?

**Comment by snosov1** [comment]
@evgeny-izutov the difference in output format is, probably, an accident?

**Comment by evgeny-izutov** [comment]
The `person-reidentification-retail-0031` model uses InnerProduct layer as final layer, so the output resolution is `[1, 256]`. The rest models are converted to support `1x1 conv` output layer (output resolution is `[1, 256, 1, 1]`). It looks like the demo use the old variant of IE API to determinate the embedding size (`256`) assuming the reversed order of `shape` operation. 
P.S. I've never seen this demo before.

**Comment by snosov1** [comment]
@Ilya-Krylov can we get away with the changes only on the demo side?

**Comment by Ilya-Krylov** [comment]
@snosov1 @kchechil I think it is possible, some kind of `reshape` operation should be added. I would propose to do this to @LeonidBeynenson as author of the demo.

**Comment by snosov1** [comment]
Marvelous idea! @LeonidBeynenson what do you think?

**Comment by LeonidBeynenson** [comment]
I created pull request https://github.com/opencv/open_model_zoo/pull/295
It contains the changes to support the reid models person-reidentification-retail-0076 and person-reidentification-retail-0079.

Please, note that the PR #295 contains models.lst file too, so if #295 is merged this PR may be closed as a duplication.

**Comment by LeonidBeynenson** [comment]
Sorry, after small talk with @Wovchena I removed my changes from  models.lst file, since now (after my PR #295) it supports all reid models and, as far as I understand, after changes by @Wovchena in #286 it supports all person detection models.

**Comment by LeonidBeynenson** [comment]
Please, note that, if I understood @Wovchena correctly, the change in models.lst file for pedestrian tracker demo (i.e. this PR) will not be required after merging @Wovchena PR #286 and my PR #295.

**Comment by IRDonch** [comment]
Closing, since this is obsoleted by the aforementioned PRs.

**Pull request closed without merging**
