### PR TITLE
Fix sample to work with YOLOv2

### PR DESCRIPTION
**Pull request by dkurt**
YOLOv2 origin:
https://pjreddie.com/darknet/yolov2/

Classes names:
https://github.com/opencv/opencv/blob/master/samples/data/dnn/object_detection_classes_yolov3.txt

https://github.com/opencv/opencv/blob/master/samples/data/dnn/object_detection_classes_pascal_voc.txt

OpenVINO's HowTo:
http://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_tf_specific_Convert_YOLO_From_Tensorflow.html

**NOTE**: For YOLOv2 `--scale 255` is required:
```
python3 mo_tf.py --input_model yolov2.pb --batch 1 \
  --tensorflow_use_custom_operations_config extensions/front/tf/yolo_v2.json \
  --scale 255
```

### CODE REVIEW

**Comment by Wovchena** [comment]
To be done:

- check if https://pjreddie.com/darknet/yolov2/ is what we are having
- is it possible to reshape output from python but not in IR, if not, this IR patching must be moved to README.md at least
- add links to labels
- clarify what's going on in the postprocessing, how should the outputs be actually processed (all this rescales)

**Comment by yssemaev** [comment]
Hi,
There is some legal limitation to re-distribute YoloV2 from DarkNet from https://pjreddie.com/darknet/yolov2/, please confirm that you do not redistribute the model, its components, sources, code snippets, data files, etc.

**Comment by vladimir-dudnik** [comment]
@dkurt could you please confirm that we do not redistribute YoloV2 from DarkNet?

**Comment by dkurt** [comment]
@yssemaev, @vladimir-dudnik, Int this patch there is no origin source code from Darknet, there is no media files or data files, no binary models.

**Comment by dkurt** [comment]
@Wovchena, Please take a look. Added a workaround for manual `.xml` editing.

**Comment by Wovchena** [comment]
I still believe that links to class labels must be added in README.md.
It would be nice to clarify what's going on in the postprocessing, how should the outputs be actually processed (all this rescales)

**Comment by dkurt** [comment]
@Wovchena, Added comments and links to labels

**Comment by IRDonch** [comment]
@dkurt Could you rebase? GitHub claims that there are merge conflicts.

**Pull request merged**
