### PR TITLE
added models for R2 release

### PR DESCRIPTION
**Pull request by atsyplen**

### CODE REVIEW

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Comment by kchechil** [comment]
cc @yssemaev

**Comment by kchechil** [comment]
@atsyplen this should be merged to develop

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Pull request closed without merging**
