### PR TITLE
The deep speech demo for OpenVINO

### PR DESCRIPTION
**Pull request by FengYen-Chang**
Implement the demo for deep speech version 0.5.0 with ctc beam search decoder. You can follow the README.md convert the model and run with your audio files, it will show the subtitle for the speech audio.

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
@FengYen-Chang thanks for your contribution to Open Model Zoo. There are some procedures we want contributors to follow. While we are still working on kind of contribution guide type of document, I'll try to put major expected steps here: first, please use OMZ develop branch for your PR, then, we want to keep general approach for Open Model Zoo as easy of use combination of tools which allow user quick and reliable way to evaluate NN models and ensure they are work in software/hardware environment, supported by OpenVINO. So, it would be better to add your model to the list of [public models](https://github.com/opencv/open_model_zoo/tree/develop/models/public) and enable it in [model downloader](https://github.com/opencv/open_model_zoo/tree/develop/tools/downloader). Note, when there is a proper model.yml in place, with required OpenVINO Model Optimizer parameters, then model can be converted to IR by converter.py script. Then put your demo code under appropriate demo [subfolder](https://github.com/opencv/open_model_zoo/tree/develop/demos/python_demos). We also use CI to automate validation for model accuracy and performance, which is able to download, convert and run basic accuracy validation of models and demos on regular base. For that purpose we expect some unification in demo application parameters (please take a look on other demo). We also expect that contributor will enable computation of accuracy metrics for his model in [accuracy_checker](https://github.com/opencv/open_model_zoo/tree/develop/tools/accuracy_checker). This will require access to some publicly available dataset/annotation with permissive license and modification of accuracy_checker to enable support of such dataset/annotation, implementation of model specific accuracy metrics (if there is no appropriate already) and pre/post-processing options.
If that is something you can accept to follow, we would be happy to review your PR and integrate into Open Model Zoo.

**Comment by FengYen-Chang** [comment]
Ok, I see, thanks for your comment, I will PR later. For this PR, do I need to close it? or just keep it?

**Comment by vladimir-dudnik** [comment]
I think you may keep this PR open, even if this is not merged yet, it may help community to see what steps are needed to run speech recognition model with OpenVINO

**Comment by FengYen-Chang** [comment]
Hi @vladimir-dudnik , 
I have a quick question about the flag sha256 in model.yml, how can I get this?

**Comment by vladimir-dudnik** [comment]
Hi @FengYen-Chang, you may compute sha256 with function hashlib.sha256(), like it is done in downloader.py at line 76 and write this value to model.yml file. Also, you need to specify size of files which will be downloaded (it is used to report progress during downloader.py work, as it may be relatively long operation)

**Comment by FengYen-Chang** [comment]
Thanks for your answer, but I am confused about what content I need to convert.

**Comment by vladimir-dudnik** [comment]
@FengYen-Chang, did not get your question. Nothing to convert. If we are still talk about model.yml file, you need to specify sha256 and size like it is done in other models in develop branch.

**Comment by FengYen-Chang** [comment]
@vladimir-dudnik, I am using downloader.py to get sha256 for deep speech model, but I just want to know what the content needs to convert to the sha256 if I don't run the downloader.py.

**Comment by FengYen-Chang** [comment]
Hi @vladimir-dudnik, I pull a new request for this, please help me to check it, thanks.

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Pull request closed without merging**
