### PR TITLE
Added octave-se-resnet-50 with alpha=0.125

### PR DESCRIPTION
**Pull request by eizamaliev**
In addition to another OctaveNets ([PR 282](https://github.com/opencv/open_model_zoo/pull/282))

### CODE REVIEW

**Comment by IRDonch** [comment]
The conversion failed. Does this need an in-development version of MO?

**Comment by eizamaliev** [comment]
@IRDonch 
Yes, and it will be in R3.

**Comment by IRDonch** [comment]
Looks good, although I won't be able to merge it until CI is updated to use a pre-release OpenVINO package.

**Comment by eizamaliev** [comment]
Ok, I agree. But it must be done till R3.

**Comment by IRDonch** [comment]
CI is updated, so let's give this a go: Jenkins please retry a build

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
CI currently fails due to `benchmark_app` changes in the new OpenVINO toolkit. I have created a pipeline branch that fixes this, and on that branch, the downloader job succeeds: http://134.191.240.124/job/omz/job/precommit/job/downloader_ubuntu16/778/console

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
The documentation job failure is due to an unrelated model, so I'm merging this.

**Pull request merged**
