### PR TITLE
Accuracy Checker: fix getting input data shape for scalar data

### PR DESCRIPTION
**Pull request by eaidova**
usually, input data for inference in accuracy checker is ndarray. But there is model NCF where input is one scalar value. This fix handles this issue.

P.S. priority is very small, the model is not in OMZ and even has not been added to public validation yet, due to another issue related to dataset conversion.

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by vladimir-dudnik** [comment]
@eaidova there are some fails on tests

**Comment by eaidova** [comment]
@vladimir-dudnik, @IRDonch  fails happend due to update pytest version.
My tests were written for pytest 4.0.0 and I need time to update them for new mock objects syntaxes.
As fast work around I can suggest to fix pytest version in setup.py

**Comment by vladimir-dudnik** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
> As fast work around I can suggest to fix pytest version in setup.py

Fine by me. In fact, I think it's a good idea to pin the test dependencies, to ensure reproducible results.

**Comment by IRDonch** [comment]
Jenkins: ok to test

**Pull request merged**
