### PR TITLE
AC: move on IE Core API

### PR DESCRIPTION
**Pull request by eaidova**
Suggested to merge after #734 to not update async policy twice
Possible improvements:
  * warning instead of error on unknown device (issue with incorrect content of available devices)

### CODE REVIEW

**Comment by vladimir-dudnik** [comment]
@eaidova there are merge conflicts

**Comment by eaidova** [comment]
@vladimir-dudnik, I know, please ignore it some time, I stay this PR only for IECore testing for now.

**Comment by eaidova** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
@eaidova Are we still supposed to ignore this or is it ready to merge?

**Comment by eaidova** [comment]
@IRDonch I will be happy to merge, but it is some kind of dangerous, because moving on IE Core API can open eye on new problems in runtime...

**Comment by eaidova** [comment]
I close this one because, I have another one with new features and fixes

**Pull request closed without merging**
