### PR TITLE
merge 2019 R1 content to master

### PR DESCRIPTION
**Pull request by vmatveic**

### CODE REVIEW

**Comment by vmatveic** [comment]
@snosov1 @kchechil @moslex @asuhov @LeonidBeynenson @grib0ed0v @evgeny-izutov @Ilya-Krylov @Wovchena

**Comment by kchechil** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
Jenkins please retry a build

**Comment by vmatveic** [comment]
Jenkins please retry a build

**Comment by kchechil** [comment]
Jenkins please retry a build

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Comment by zmaslova** [comment]
accuracy checker precommit is red because it's removed in this PR. Is this expected?

**Comment by kchechil** [comment]
@zmaslova yes, in R1 it is delivered as https://github.com/opencv/dldt/tree/2019/tools/accuracy_checker . My suggestion is to suppress accuracy_checker CI for now until we finalize its movement.
@snosov1  @IRDonch  what's the final naming convention for folder for tools like that ? https://github.com/opencv/open_model_zoo/tree/master/tools/<tool_name>/ ?

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Comment by snosov1** [comment]
> what's the final naming convention for folder for tools like that ? 

I'd leave it up to @IRDonch . Your proposal is fine by me.

**Comment by IRDonch** [comment]
> I'd leave it up to @IRDonch . Your proposal is fine by me.

Sounds good to me, as well.

**Pull request merged**
