### PR TITLE
Add supporting reid models with NCHW layout to pedestrian_tracker_demo

### PR DESCRIPTION
**Pull request by LeonidBeynenson**
Earlier only models with NC layout were supported.

### CODE REVIEW

**Comment by LeonidBeynenson** [comment]
Please, note that now all person reid models are supported:
* person-reidentification-retail-0031, 
* person-reidentification-retail-0076, 
* person-reidentification-retail-0079.

**Comment by LeonidBeynenson** [comment]
Add commit to specify models for the pedestrian tracker demo to its models.lst file

**Comment by LeonidBeynenson** [comment]
After small talk with  @Wovchena I removed my changes in models.lst file, since now (after my PR #295) it supports all reid models and, as far as I understand, after changes by @Wovchena in #286 it supports all person detection models.

**Comment by LeonidBeynenson** [comment]
Jenkins please retry a build

**Comment by IRDonch** [comment]
@LeonidBeynenson Please add test cases with the newly supported models to `demos/tests/cases.py`.

**Comment by IRDonch** [comment]
Jenkins: ok to test

**Pull request merged**
