### PR TITLE
AC: support PRNet

### PR DESCRIPTION
**Pull request by eaidova**

### CODE REVIEW

**Comment by kchechil** [comment]
@eaidova  when it is planned to merge this? is there any result of accuracy validation?

**Comment by eaidova** [comment]
@kchechil  working on this model stopped due to legal issue cc @yssemaev  (repo code has MIT license, model is research only).

**Comment by eaidova** [comment]
@kchechil  accuracy checker support done, config and results for model I share with you in internal repo.

**Comment by vladimir-dudnik** [comment]
@eaidova please resolve conflicts

**Comment by eaidova** [comment]
> @eaidova please resolve conflicts

@vladimir-dudnik , done

**Comment by eaidova** [comment]
@vladimir-dudnik  can we merge it?

**Pull request merged**
