### PR TITLE
Patch 19

### PR DESCRIPTION
**Pull request by aalborov**

### CODE REVIEW

**Comment by zmaslova** [comment]
@aalborov please change target branch to develop

**Comment by kchechil** [comment]
@aalborov @yssemaev @vmatveic as there is no answer for 2 weeks, can we close this PR without merge?
The content is completely unclear and most likely outdated.

**Comment by vmatveic** [comment]
I've changed the target branch to develop. And we've got just one file of diff. I think it should be reviewe and merged if it's ok. @aalborov , please comment asap! Also, please resolve merge conflicts here. Thanks!

**Comment by kchechil** [comment]
@aalborov @vmatveic please resolve conflicts.

**Comment by kchechil** [comment]
Jenkins please retry a build

**Pull request merged**
