### PR TITLE
 Added brain-tumor-segmentation model to the topology list

### PR DESCRIPTION
**Pull request by lachinov**

### CODE REVIEW

**Comment by zmaslova** [comment]
Jenkins please retry a build

**Comment by snosov1** [comment]
@zmaslova Zoya, good to merge?

**Comment by zmaslova** [comment]
@snosov1 LGTM, but model_optimizer_args should be rewritten (look at current master)

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Comment by atsyplen** [comment]
@lachinov and now please move your topology from end of the configuration file and insert before started intel models

**Comment by atsyplen** [comment]
Jenkins please retry a build

**Pull request merged**
